### PR TITLE
Fixing the stack trace printing issue

### LINKED ISSUE #43: Do not print unnecessary stack traces
The issue: printing out the stack trace instead of a user-friendly error message and the help menu

The fix: Modify how which error is being thrown in AbstractDominoCommand

### PR DESCRIPTION
**Pull request by ctgao**
Fix #43 

The issue: printing out the stack trace instead of a user-friendly error message and the help menu

The fix: Modify how which error is being thrown in AbstractDominoCommand

Old Code flow: 
In “getRequiredParam”, the function “Validate.notBlank” will either throw a NullPointerException or an IllegalArgumentException upon two different non valid input types. NullPointerException is thrown when the argument hasn’t been specified at all (ie: domino job get) and the IllegalArgumentException is thrown when the input is considered “blank” (ie: domino job get jobId). If the error thrown is a NullPointerException, it goes into the broad “Exception e” catch statement and just throws a RuntimeError, showing the stack trace.

New Code flow:
In “getRequiredParam”, when the “Validate.notBlank” function throws an exception, catch it and throw an IllegalArgumentException with a message. The IllegalArgumentException gets tossed up to the built in PicoCLI parameters exception handler. That will print out the error message (in red) and also display the help menu.

### CODE REVIEW

File: src/main/java/com/ksm/domino/cli/command/AbstractDominoCommand.java [hunk 1]
```diff
@@ -125,8 +118,12 @@ public void output(Object o, Domino domino) throws JsonProcessingException {
 
     public String getRequiredParam(Map<String, String> parameters, String parameterName, String command) {
         String param = parameters.get(parameterName);
-        Validate.notBlank(param,
+        try {
+            Validate.notBlank(param,
                     String.format("Missing the required parameter '%s' when calling '%s'.", parameterName, command));
+        } catch (Exception e) {
+            throw new IllegalArgumentException(e.getMessage());
+        }
```
Comment (melloware) [inline src/main/java/com/ksm/domino/cli/command/AbstractDominoCommand.java:126]: I think instead of Validate.notBlank we can do...

```java
if (StringUtils.isBlank(param)) {
   throw new IllegalArgumentException(String.format("Missing the required parameter '%s' when calling '%s'.", parameterName, command));
}

**Review by melloware — CHANGES_REQUESTED** [review]

**Review by melloware — APPROVED** [review]
